package com.example.designsystem.theme.theme

import androidx.compose.runtime.Stable
import androidx.compose.ui.graphics.Color

// @Stable 인 이유: 다크모드로의 전환
@Stable
data class CleaningLabColor(
    val primaryNormal: Color,
    val accentRed1: Color,
    val accentRed2: Color,
    val backgroundWhite: Color,
    val backgroundGray: Color,
    val lineTab: Color,
    val lineNav: Color,
    val lineAssist1: Color,
    val lineAssist2: Color,
    val lineSection1: Color,
    val lineSection1Assist: Color,
    val lineSection2: Color,
    val labelNormal1: Color,
    val labelNormal2: Color,
    val labelNormal3: Color,
    val labelNormal4: Color,
    val labelStrong: Color,
    val componentFillWhite: Color,
    val componentFillGray: Color,
    val componentFillBlue1: Color,
    val componentFillBlue2: Color,
    val componentFillBlue3: Color,
    val componentOutlineGray1: Color,
    val componentOutlineGray2: Color,
    val iconWhite: Color,
    val iconBlack1: Color,
    val iconBlack2: Color,
    val iconGray1: Color,
    val iconGray2: Color,
    val iconPrimary1: Color,
    val iconPrimary2: Color,
    val dimmerNormal: Color,
    val staticWhite: Color,
    val staticBlack: Color,
)

val CleaningLabLightColor = CleaningLabColor(
    primaryNormal = Color(0xFF00BED6),
    accentRed1 = Color(0xFFFF5152),
    accentRed2 = Color(0xFFFF6B6B),
    backgroundWhite = Color(0xFFFFFFFF),
    backgroundGray = Color(0xFFF2F2F2),
    lineTab = Color(0xFFCCCCCC),
    lineNav = Color(0xFFDCDCDC),
    lineAssist1 = Color(0xFFE5E5E5),
    lineAssist2 = Color(0xFFF0F0F0),
    lineSection1 = Color(0xFFF2F2F2),
    lineSection1Assist = Color(0xFFE4E4E4),
    lineSection2 = Color(0xFFF1F1F1),
    labelNormal1 = Color(0xFF262626),
    labelNormal2 = Color(0xFF666666),
    labelNormal3 = Color(0xFF999999),
    labelNormal4 = Color(0xFFFFFFFF),
    labelStrong = Color(0xFF2C2B31),
    componentFillWhite = Color(0xFFFFFFFF),
    componentFillGray = Color(0xFFF7F7F7),
    componentFillBlue1 = Color(0xFF004B82),
    componentFillBlue2 = Color(0xFF414B4C),
    componentFillBlue3 = Color(0xFF43484C),
    componentOutlineGray1 = Color(0xFFE5E5E5),
    componentOutlineGray2 = Color(0xFFF0F0F0),
    iconWhite = Color(0xFFFFFFFF),
    iconBlack1 = Color(0xFF262626),
    iconBlack2 = Color(0xFF333333),
    iconGray1 = Color(0xFF999999),
    iconGray2 = Color(0xFFCCCCCC),
    iconPrimary1 = Color(0xFF0FB8CD),
    iconPrimary2 = Color(0xFFE8F6F7),
    dimmerNormal = Color(0xFF000000).copy(0.6f),
    staticWhite = Color(0xFFFFFFFF),
    staticBlack = Color(0xFF000000),
)
