package com.example.designsystem.theme.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp

// 외부에서 생성할 수 없음
@Immutable
class CleaningLabTypography internal constructor(
    val display: TextStyle = TextStyle(),
    val headline1: TextStyle = TextStyle(),
    val headline2: TextStyle = TextStyle(),
    val title1: TextStyle = TextStyle(),
    val title2: TextStyle = TextStyle(),
    val title3: TextStyle = TextStyle(),
    val title4: TextStyle = TextStyle(),
    val body1: TextStyle = TextStyle(),
    val body2: TextStyle = TextStyle(),
    val body3: TextStyle = TextStyle(),
    val body4: TextStyle = TextStyle(),
    val body5: TextStyle = TextStyle(),
    val body6: TextStyle = TextStyle(),
    val body7: TextStyle = TextStyle(),
    val body8: TextStyle = TextStyle(),
    val label1: TextStyle = TextStyle(),
    val label2: TextStyle = TextStyle(),
    val label3: TextStyle = TextStyle(),
    val label4: TextStyle = TextStyle(),
    val label5: TextStyle = TextStyle(),
    val label6: TextStyle = TextStyle(),
) {
    constructor() : this(
        display = TextStyle(
            fontSize = 28.sp,
            lineHeight = 40.sp,
            letterSpacing = 0.002.em,
            fontWeight = FontWeight.Bold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        headline1 = TextStyle(
            fontSize = 28.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.002.em,
            fontWeight = FontWeight.Bold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        headline2 = TextStyle(
            fontSize = 27.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.01.em,
            fontWeight = FontWeight.Bold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        title1 = TextStyle(
            fontSize = 24.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.em,
            fontWeight = FontWeight.Bold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        title2 = TextStyle(
            fontSize = 21.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.01.em,
            fontWeight = FontWeight.SemiBold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        title3 = TextStyle(
            fontSize = 18.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.05.em,
            fontWeight = FontWeight.Bold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        title4 = TextStyle(
            fontSize = 15.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.03.em,
            fontWeight = FontWeight.SemiBold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        body1 = TextStyle(
            fontSize = 21.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.01.em,
            fontWeight = FontWeight.SemiBold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        body2 = TextStyle(
            fontSize = 19.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.em,
            fontWeight = FontWeight.Normal,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        body3 = TextStyle(
            fontSize = 18.sp,
            lineHeight = 1.5.em,
            letterSpacing = -(0.01).em,
            fontWeight = FontWeight.Bold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        body4 = TextStyle(
            fontSize = 18.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.em,
            fontWeight = FontWeight.Normal,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        body5 = TextStyle(
            fontSize = 17.sp,
            lineHeight = 1.5.em,
            letterSpacing = -(0.015).em,
            fontWeight = FontWeight.Normal,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        body6 = TextStyle(
            fontSize = 16.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.03.em,
            fontWeight = FontWeight.Normal,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        body7 = TextStyle(
            fontSize = 16.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.025.em,
            fontWeight = FontWeight.Normal,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        body8 = TextStyle(
            fontSize = 16.sp,
            lineHeight = 1.5.em,
            letterSpacing = -(0.01).em,
            fontWeight = FontWeight.Normal,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        label1 = TextStyle(
            fontSize = 19.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.em,
            fontWeight = FontWeight.Bold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        label2 = TextStyle(
            fontSize = 17.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.em,
            fontWeight = FontWeight.Bold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        label3 = TextStyle(
            fontSize = 17.sp,
            lineHeight = 1.5.em,
            letterSpacing = -(0.01).em,
            fontWeight = FontWeight.SemiBold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        label4 = TextStyle(
            fontSize = 17.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.em,
            fontWeight = FontWeight.Normal,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        label5 = TextStyle(
            fontSize = 12.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.em,
            fontWeight = FontWeight.Bold,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
        label6 = TextStyle(
            fontSize = 12.sp,
            lineHeight = 1.5.em,
            letterSpacing = 0.03.em,
            fontWeight = FontWeight.Normal,
            fontFamily = pretendard,
            lineHeightStyle = lineHeightStyle,
            platformStyle = platformTextStyle,
        ),
    )
}
